"use client";

import "./processing.css";
import "./quality.css";

import {useEffect, useMemo, useState, type CSSProperties, type FormEvent} from "react";
import {ParserLab} from "./parser-lab";
import {Input} from "@/components/ui/input";
import {Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle} from "@/components/ui/dialog";
import {AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger} from "@/components/ui/alert-dialog";
import {buildAnalytics, gameCharacters, processingRate, type ProcessingMetrics} from "@/lib/analytics";
import {matchesQualityFilter, qualityIssues, qualityPriority, type QualityCandidate, type QualityFilter, type QualityIssue} from "@/lib/data-quality";
import {localeNames, translator, type Locale, type MessageKey} from "@/lib/i18n";
import {buildRecordProgression, topRankingsByCharacter, type RankingRow} from "@/lib/ranking";
import {canonicalizePlayerNick} from "@/lib/player-nick";
import {buildGitHubSubmissionUrl, isYouTubeUrl} from "@/lib/submission";
import {buildPerformanceTiers} from "@/lib/tier-list";
import {digitsOnly,parseTimeParts,splitTimeLabel} from "@/lib/time-input";
import {getVideoPreview} from "@/lib/video";

declare const __PUBLIC_READ_ONLY__: boolean;
const publicReadOnly=typeof __PUBLIC_READ_ONLY__!=="undefined"&&__PUBLIC_READ_ONLY__;
type Tab="overview"|"queue"|"rankings"|"tiers"|"parser"|"history"|"submit";
type T=ReturnType<typeof translator>;
type Run=QualityCandidate&{id:number;user:string;char:string;map:string;time:string;status:string;conf:number;videoId:string;title:string;current:string;publishedAt:string|null;createdAt:string|null};
type ApiCandidate={id:number;video_id:string;title:string;channel:string|null;player_nick:string|null;character:string|null;category:string|null;floor:number|null;time_ms:number|null;confidence:number;status:string;published_at:string|null;created_at:string|null;ocr_outcome:string|null;possible_duplicate:number;benchmark_ms:number|null;benchmark_count:number|null};

const demoData:Run[]=[
  {id:1,user:"Borkaz",char:"Ereb",map:"Void Invasion · 3F",time:"01:32",status:"ready_for_review",conf:98,videoId:"WZeUJAw4pmU",title:"Ereb | Vazio (Invasão) 3f (1'32) | Grand Chase Classic",current:"—",publishedAt:null,createdAt:null,character:"Ereb",category:"void_invasion",floor:3,time_ms:92000,confidence:.98},
  {id:2,user:"Borkaz",char:"Ereb",map:"Void Nightmare · 4F",time:"—",status:"time_required",conf:86,videoId:"V6O_9x6QTvw",title:"Ereb | Vazio (Pesadelo) 4F | Grand Chase Classic",current:"—",publishedAt:null,createdAt:null,character:"Ereb",category:"void_nightmare",floor:4,time_ms:null,confidence:.86},
];
const dungeons=[
  {key:"void_invasion:3",category:"void_invasion",floor:3,label:"Void Invasion · 3F"},
  {key:"void_taint:3",category:"void_taint",floor:3,label:"Void Taint · 3F"},
  {key:"void_nightmare:4",category:"void_nightmare",floor:4,label:"Void Nightmare · 4F"},
  {key:"void_apocalypse:3",category:"void_apocalypse",floor:3,label:"Void Apocalypse · 3F"},
  {key:"tower_of_disappearance:0",category:"tower_of_disappearance",floor:0,label:"Tower of Disappearance · Hard"},
  {key:"duel_4:0",category:"duel_4",floor:0,label:"Duel 4"},
  {key:"loj_unlimited:0",category:"loj_unlimited",floor:0,label:"LoJ Unlimited"},
  {key:"infinity_cloister_3:0",category:"infinity_cloister_3",floor:0,label:"Infinity Cloister · Stage 3"},
  {key:"land_of_judgement:0",category:"land_of_judgement",floor:0,label:"Land of Judgement"},
  {key:"renaks_core_champion:0",category:"renaks_core_champion",floor:0,label:"Renak's Core · Champion"},
  {key:"great_explosion_of_kounat:0",category:"great_explosion_of_kounat",floor:0,label:"Great Explosion of Kounat"},
  {key:"wizards_labyrinth_30:0",category:"wizards_labyrinth_30",floor:0,label:"Wizard's Labyrinth · Stage 30"},
  {key:"moonlight_village:0",category:"moonlight_village",floor:0,label:"Moonlight Village"},
  {key:"temple_of_time:0",category:"temple_of_time",floor:0,label:"Temple of Time"},
  {key:"sanctuary_divine_beast_master:0",category:"sanctuary_divine_beast_master",floor:0,label:"Sanctuary of Divine Beast · Master"},
  {key:"hall_of_harmony_master:0",category:"hall_of_harmony_master",floor:0,label:"Hall of Harmony · Master"},
  {key:"chapel_of_eternity_master:0",category:"chapel_of_eternity_master",floor:0,label:"Chapel of Eternity · Master"},
  {key:"path_shrouded_darkness_master:0",category:"path_shrouded_darkness_master",floor:0,label:"Path Shrouded in Darkness · Master"},
  {key:"apocalypse_vortex_master:0",category:"apocalypse_vortex_master",floor:0,label:"Apocalypse Vortex · Master"},
  {key:"berkas_lair:0",category:"berkas_lair",floor:0,label:"Berkas' Lair"},
  {key:"angry_boss_archimedia:0",category:"angry_boss_archimedia",floor:0,label:"Angry Boss · Archimedia"},
  {key:"angry_boss_alcubra:0",category:"angry_boss_alcubra",floor:0,label:"Angry Boss · Alcubra"},
];
const tabKeys:Record<Tab,MessageKey>={overview:"overview",queue:"queue",rankings:"rankings",tiers:"tiers",parser:"parser",history:"history",submit:"submit"};
const tabIcons:Record<Tab,string>={overview:"⌁",queue:"▣",rankings:"♕",tiers:"S",parser:"⌘",history:"↗",submit:"＋"};
const categoryName=(value:string|null)=>value?value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";
const timeLabel=(ms:number|null)=>ms===null?"—":`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`;
const toRun=(r:ApiCandidate):Run=>({id:r.id,user:r.player_nick??r.channel??"—",char:r.character??"—",map:`${categoryName(r.category)}${r.floor?` · ${r.floor}F`:""}`,time:timeLabel(r.time_ms),status:r.status,conf:Math.round(r.confidence*100),videoId:r.video_id,title:r.title,current:"—",publishedAt:r.published_at,createdAt:r.created_at,character:r.character,category:r.category,floor:r.floor,time_ms:r.time_ms,confidence:r.confidence,ocr_outcome:r.ocr_outcome,possible_duplicate:r.possible_duplicate,benchmark_ms:r.benchmark_ms,benchmark_count:r.benchmark_count});

export default function Home(){
  const[locale,setLocale]=useState<Locale>("pt"),[tab,setTab]=useState<Tab>(publicReadOnly?"overview":"queue"),[runs,setRuns]=useState<Run[]>(publicReadOnly?[]:demoData),[sel,setSel]=useState<Run|null>(publicReadOnly?null:demoData[0]),[rankings,setRankings]=useState<RankingRow[]>([]),[history,setHistory]=useState<RankingRow[]>([]),[processing,setProcessing]=useState<ProcessingMetrics|null>(null),[connected,setConnected]=useState(false),[msg,setMsg]=useState("");
  const t=translator(locale),tabs:Tab[]=publicReadOnly?["overview","rankings","tiers","history","submit"]:["overview","queue","rankings","tiers","parser","history"],dataUrl=publicReadOnly?"/candidates.json":"/api/candidates";
  useEffect(()=>{const stored=localStorage.getItem("gc-radar-locale") as Locale|null,detected=navigator.language.startsWith("ko")?"ko":navigator.language.startsWith("th")?"th":navigator.language.startsWith("en")?"en":"pt",next=stored&&stored in localeNames?stored:detected;setLocale(next);document.documentElement.lang=next},[]);
  useEffect(()=>{fetch(dataUrl,{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();const body=await response.json();const liveRuns=(body.candidates??[] as ApiCandidate[]).map(toRun),normalize=(row:RankingRow)=>({...row,player_nick:canonicalizePlayerNick(row.player_nick)??row.player_nick});setRuns(liveRuns);setSel(liveRuns[0]??null);setRankings((body.rankings??[] as RankingRow[]).map(normalize));setHistory((body.history??body.rankings??[] as RankingRow[]).map(normalize));setProcessing(body.processing??null);setConnected(true)}).catch(()=>setConnected(false))},[dataUrl]);
  const changeLocale=(next:Locale)=>{setLocale(next);localStorage.setItem("gc-radar-locale",next);document.documentElement.lang=next};
  const flash=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(""),2500)};
  const decide=async(ok:boolean,timeMs?:number)=>{if(!sel)return;try{const response=await fetch(`/api/candidates/${sel.id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approved:ok,time_ms:timeMs})});if(!response.ok)throw new Error((await response.json()).error);setRuns(current=>current.filter(x=>x.id!==sel.id));setSel(null);flash(ok?t("approve"):t("reject"))}catch(error){flash(error instanceof Error?error.message:t("unavailable"))}};
  const revoke=async(run:RankingRow)=>{try{const response=await fetch(`/api/rankings/${run.id}/revoke`,{method:"POST"});if(!response.ok)throw new Error((await response.json()).error);setRankings(current=>current.filter(item=>item.id!==run.id));setHistory(current=>current.filter(item=>item.id!==run.id));flash(t("runRemoved"));return true}catch(error){flash(error instanceof Error?error.message:t("unavailable"));return false}};
  return <main><aside><div className="brand"><i>◎</i><span><b>GC Run Radar</b><small>Speedrun intelligence</small></span></div><nav>{tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}><i>{tabIcons[item]}</i><span>{t(tabKeys[item])}</span>{item==="queue"&&<em>{runs.length}</em>}</button>)}</nav><div className="profile"><i>{publicReadOnly?"GC":"GS"}</i><span><b>{publicReadOnly?t("publicAccess"):"Gabriel"}</b><small>{publicReadOnly?t("readOnly"):t("admin")}</small></span></div></aside>
    <section className="work"><header><div><p>{t(publicReadOnly?"community":"monitoring")}</p><h1>{t(tabKeys[tab])}</h1></div><div className="headerActions"><span className="live">● {connected?t(publicReadOnly?"updated":"connected"):t("unavailable")}</span><label className="languageControl"><span>{t("language")}</span><select value={locale} onChange={event=>changeLocale(event.target.value as Locale)} aria-label={t("language")}>{(Object.keys(localeNames) as Locale[]).map(code=><option value={code} key={code}>{localeNames[code]}</option>)}</select></label><button onClick={()=>location.reload()}>⌕ {t("refresh")}</button></div></header>
      {tab==="overview"?<Analytics rankings={rankings} processing={processing} connected={connected} t={t}/>:tab==="queue"&&!publicReadOnly?<Queue runs={runs} sel={sel} setSel={setSel} decide={decide} t={t}/>:tab==="rankings"?<Ranking rankings={rankings} connected={connected} onRevoke={publicReadOnly?undefined:revoke} t={t}/>:tab==="tiers"?<TierList rankings={rankings} connected={connected} onRevoke={publicReadOnly?undefined:revoke} t={t}/>:tab==="parser"&&!publicReadOnly?<ParserLab t={t}/>:tab==="submit"&&publicReadOnly?<SubmissionForm t={t}/>:<History rows={history} connected={connected} locale={locale} t={t}/>}<footer><a href="https://syntax817.github.io/leaderboard/" target="_blank" rel="noreferrer">{t("inspired")}</a><span>{publicReadOnly?t("publicFooter"):connected?t("queueFooter",{count:runs.length}):t("unavailable")}</span></footer></section>{msg&&<div className="toast">✓ {msg}</div>}</main>
}

function Analytics({rankings,processing,connected,t}:{rankings:RankingRow[],processing:ProcessingMetrics|null,connected:boolean,t:T}){
  const[era,setEra]=useState("all"),data=buildAnalytics(rankings,dungeons,era),eraLabel=era==="current"?t("currentEra"):era==="syntaxii_2026_archive"?t("archive"):t("allEras");
  return <section className="analyticsPage"><div className="analyticsIntro"><div><p>{t("datasetCoverage")}</p><h2>{t("panorama")}</h2><span>{t("panoramaSub")}</span></div><SelectEra era={era} setEra={setEra} t={t}/></div>{!connected?<EmptyState title={t("loadingAnalytics")} subtitle={t("loadingSub")}/>:<><section className="analyticsStats"><Metric label={t("verifiedRuns")} value={String(data.verifiedRuns)} note={eraLabel}/><Metric label={t("characters")} value={`${data.representedCharacters}/${gameCharacters.length}`} note={t("withRun")}/><Metric label={t("uniquePlayers")} value={String(data.uniquePlayers)} note={t("identifiedNicks")}/><Metric label={t("topFilled")} value={`${data.overallCoveragePercent}%`} note={t("positions",{filled:data.totalFilledSlots,total:data.totalSlots})}/></section>{processing&&<ProcessingPanel metrics={processing} t={t}/>}<section className="analyticsGrid"><article className="coveragePanel"><div className="analyticsHead"><div><small>{t("coverageDungeon")}</small><h3>{t("rankingDepth")}</h3></div><span>{t("withData",{active:data.activeDungeons,total:dungeons.length})}</span></div><div className="dungeonBars">{data.boards.map(board=><div className="dungeonBar" key={board.key}><div><strong>{board.label}</strong><small>{t("characterCount",{count:board.representedCharacters,filled:board.filledSlots})}</small></div><b>{board.coveragePercent}%</b><span><i style={{width:`${board.coveragePercent}%`}}/></span></div>)}</div></article><article className="insightPanel"><small>{t("quickRead")}</small><h3>{bestCoverageInsight(data.boards,t)}</h3><p>{coverageRecommendation(data.boards,t)}</p><div><span>0</span><i/><span>1</span><i/><span>2</span><i/><span>3</span><i/><span>4 {t("times")}</span></div></article></section><section className="heatmapPanel"><div className="analyticsHead"><div><small>{t("matrix")}</small><h3>{t("coverageMap")}</h3></div><span>{t("cellHelp")}</span></div><div className="heatmapScroll"><div className="heatmap" style={{"--dungeon-count":dungeons.length} as CSSProperties}><b className="heatCorner">{t("character")}</b>{dungeons.map(dungeon=><b className="heatColumn" title={dungeon.label} key={dungeon.key}>{shortDungeon(dungeon.category)}</b>)}{gameCharacters.map(character=><div className="heatRow" key={character}><strong>{character}</strong>{data.boards.map(board=>{const count=board.byCharacter.get(character)??0;return <span className={`heatCell level${count}`} title={`${character} · ${board.label}: ${count}/4`} aria-label={`${character}, ${board.label}, ${count}/4`} key={board.key}>{count}</span>})}</div>)}</div></div><p className="analyticsNote">{t("emptyPriority")}</p></section></>}</section>
}

function ProcessingPanel({metrics,t}:{metrics:ProcessingMetrics,t:T}){
  const stages=[
    ["discoveredStage",metrics.discovered],
    ["classifiedStage",metrics.classified],
    ["timedStage",metrics.timed],
    ["approvedStage",metrics.approved],
    ["rankedStage",metrics.ranked],
  ] as const;
  const ocrRate=processingRate(metrics.ocr_matched,metrics.ocr_attempted);
  const evidenceTotal=metrics.title_times+metrics.ocr_matched+metrics.human_times;
  const sources=[
    ["titleSource",metrics.title_times,"title"],
    ["ocrSource",metrics.ocr_matched,"ocr"],
    ["humanSource",metrics.human_times,"human"],
  ] as const;
  return <section className="processingPanel"><div className="analyticsHead"><div><small>{t("processingPipeline")}</small><h3>{t("processingFunnel")}</h3></div><span>{metrics.last_updated?t("lastUpdated",{date:metrics.last_updated.slice(0,16).replace("T"," ")}):t("liveSnapshot")}</span></div><div className="processingLayout"><div className="funnel" aria-label={t("processingFunnel")}>{stages.map(([label,value])=><div key={label}><span><strong>{t(label)}</strong><small>{processingRate(value,metrics.discovered)}%</small></span><i><b style={{width:`${processingRate(value,metrics.discovered)}%`}}/></i><em>{value}</em></div>)}</div><aside className="processingAside"><div className="ocrScore"><span><small>{t("ocrSuccess")}</small><strong>{ocrRate}%</strong></span><p>{t("ocrResult",{matched:metrics.ocr_matched,attempted:metrics.ocr_attempted})}</p><em>{t("manualPending",{count:metrics.pending_manual})}</em></div><div className="sourceBreakdown"><small>{t("timeSources")}</small>{sources.map(([label,value,kind])=><div key={label}><span className={kind}/><b>{t(label)}</b><em>{value}</em><i><b className={kind} style={{width:`${processingRate(value,evidenceTotal)}%`}}/></i></div>)}</div></aside></div><p className="processingNote">{t("pipelineMethod")}</p></section>
}

function History({rows,connected,locale,t}:{rows:RankingRow[],connected:boolean,locale:Locale,t:T}){const[era,setEra]=useState("all"),[dungeonKey,setDungeonKey]=useState(dungeons[0].key),[character,setCharacter]=useState("all"),dungeon=dungeons.find(item=>item.key===dungeonKey)??dungeons[0],characters=useMemo(()=>[...new Set(rows.filter(row=>row.category===dungeon.category&&row.floor===dungeon.floor).map(row=>row.character))].sort((a,b)=>a.localeCompare(b)),[rows,dungeon.category,dungeon.floor]),events=buildRecordProgression(rows,dungeon.category,dungeon.floor,character,era),current=character==="all"?null:events[0];useEffect(()=>{if(character!=="all"&&!characters.includes(character))setCharacter("all")},[characters,character]);return <section className="historyPage"><div className="historyIntro"><div><p>{dungeon.label.toUpperCase()}</p><h2>{t("historyTitle")}</h2><span>{t("historySub")}</span></div><div className="historyFilters"><label>{t("dungeon")}<select value={dungeonKey} onChange={event=>setDungeonKey(event.target.value)}>{dungeons.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><label>{t("chooseCharacter")}<select value={character} onChange={event=>setCharacter(event.target.value)}><option value="all">{t("allCharacters")}</option>{characters.map(name=><option value={name} key={name}>{name}</option>)}</select></label><SelectEra era={era} setEra={setEra} t={t}/></div></div>{connected&&events.length?<><div className="historySummary"><span>{t("recordChanges",{count:events.length})}</span>{current&&<b>{t("fastestNow",{time:timeLabel(current.time_ms)})}</b>}</div><div className="timeline">{events.map(event=><article key={event.id}><i/><div className="timelineDate">{event.event_at?formatDate(event.event_at,locale):t("unknownDate")}</div><div className="timelineCard"><div><small>{event.era_key==="current"?t("currentEra"):t("archive")}</small><h3>{event.character} · {event.player_nick}</h3><span>{event.improvement_ms===null?t("firstRecord"):t("improvedBy",{seconds:(event.improvement_ms/1000).toFixed(event.improvement_ms%1000?1:0)})}</span></div><time>{timeLabel(event.time_ms)}</time>{event.video_url&&<a href={event.video_url} target="_blank" rel="noreferrer">▶ {t("watch")}</a>}</div></article>)}</div></>:<EmptyState title={connected?t("noHistory"):t("loadingAnalytics")} subtitle={connected?t("noHistorySub"):t("loadingSub")}/>}</section>}

function Ranking({rankings,connected,onRevoke,t}:{rankings:RankingRow[],connected:boolean,onRevoke?:RevokeRun,t:T}){const[era,setEra]=useState("all"),[dungeonKey,setDungeonKey]=useState(dungeons[0].key),[selectedRun,setSelectedRun]=useState<RankingRow|null>(null),dungeon=dungeons.find(x=>x.key===dungeonKey)??dungeons[0],groups=topRankingsByCharacter(rankings,dungeon.category,dungeon.floor,era);return <section className="rankingPage"><div className="rankingIntro"><div><p>{dungeon.label.toUpperCase()}</p><h2>{t("topByCharacter")}</h2><span>{t("rankingSub")}</span></div><div className="rankingFilters"><label>{t("dungeon")}<select value={dungeonKey} onChange={e=>setDungeonKey(e.target.value)}>{dungeons.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><SelectEra era={era} setEra={setEra} t={t}/></div></div><div className="eraNote"><b>{era==="current"?t("currentEra"):era==="all"?t("generalHistory"):t("archive")}</b><span>{era==="current"?t("currentEraNote"):t("archiveNote")}</span></div>{groups.length?<div className="characterGrid">{groups.map(group=><article className="characterBoard" style={{"--character":"#59e1d9"} as CSSProperties} key={group.character}><header><div><small>{t("character").toUpperCase()}</small><h3>{group.character}</h3></div><span>{group.runs.length}/4 {t("times")}</span></header><div className="podium">{Array.from({length:4},(_,i)=>{const run=group.runs[i];return <div className={i===0&&run?"rankRow champion":"rankRow"} key={i}><b>#{i+1}</b>{run?<><span><button className="rankNick" type="button" onClick={()=>setSelectedRun(run)} disabled={!run.video_url&&!onRevoke} aria-label={t("openRunVideo",{nick:run.player_nick})}>{run.player_nick}<i aria-hidden="true">▶</i>{i===0&&<em>{t("record")}</em>}</button><small>{run.video_url?t("clickForEvidence"):t("verified")}</small></span><time>{timeLabel(run.time_ms)}</time></>:<><span className="open"><strong>{t("openSlot")}</strong><small>{t("waitingRun")}</small></span><time>—</time></>}</div>})}</div></article>)}</div>:<EmptyState title={connected?t("noApproved"):t("loadingAnalytics")} subtitle={connected?t("candidatesFirst"):t("loadingSub")}/>}<p className="rankingFootnote">{t("openSlotsNote")}</p><RunEvidenceDialog run={selectedRun} dungeon={dungeon.label} setOpen={open=>{if(!open)setSelectedRun(null)}} onRevoke={onRevoke} t={t}/></section>}

type RevokeRun=(run:RankingRow)=>Promise<boolean>;

function RunEvidenceDialog({run,dungeon,setOpen,onRevoke,t}:{run:RankingRow|null,dungeon:string,setOpen:(open:boolean)=>void,onRevoke?:RevokeRun,t:T}){const preview=run?.video_url?getVideoPreview(run.video_url):null;return <Dialog open={run!==null} onOpenChange={setOpen}><DialogContent className="runEvidenceDialog"><DialogHeader><span className="evidenceEyebrow">{t("runEvidence")}</span><DialogTitle>{run?.player_nick??"—"}</DialogTitle><DialogDescription>{run?t("evidenceSummary",{character:run.character,dungeon,time:timeLabel(run.time_ms)}):""}</DialogDescription></DialogHeader>{run&&<>{preview&&<a className={`evidencePreview${preview.thumbnailUrl?" hasThumbnail":""}`} href={preview.watchUrl} target="_blank" rel="noreferrer" aria-label={t("watchOn",{platform:preview.platform})}>{preview.thumbnailUrl?<img src={preview.thumbnailUrl} alt={t("videoThumbnail",{nick:run.player_nick})}/>:<div><b>{preview.platform}</b><span>{t("previewUnavailable")}</span></div>}<i aria-hidden="true">▶</i><em>{timeLabel(run.time_ms)}</em></a>}<div className="evidenceMeta"><div><small>{t("character")}</small><b>{run.character}</b></div><div><small>{t("dungeon")}</small><b>{dungeon}</b></div><div><small>{t("channel")}</small><b>{run.channel??run.player_nick}</b></div><div><small>{t("confirmedTimeLabel")}</small><b>{timeLabel(run.time_ms)}</b></div></div><div className="evidenceActions">{preview&&<a className="watchEvidence" href={preview.watchUrl} target="_blank" rel="noreferrer">▶ {t("watchOn",{platform:preview.platform})}</a>}{onRevoke&&<AlertDialog><AlertDialogTrigger className="removeRunButton">⌫ {t("removeRun")}</AlertDialogTrigger><AlertDialogContent className="revokeDialog"><AlertDialogHeader><AlertDialogTitle>{t("revokeTitle")}</AlertDialogTitle><AlertDialogDescription>{t("revokeDescription",{nick:run.player_nick,time:timeLabel(run.time_ms)})}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t("cancel")}</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={async()=>{if(await onRevoke(run))setOpen(false)}}>{t("confirmRemoval")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></>}</DialogContent></Dialog>}

function TierList({rankings,connected,onRevoke,t}:{rankings:RankingRow[],connected:boolean,onRevoke?:RevokeRun,t:T}){const[era,setEra]=useState("all"),[dungeonKey,setDungeonKey]=useState(dungeons[0].key),[selectedRun,setSelectedRun]=useState<RankingRow|null>(null),dungeon=dungeons.find(item=>item.key===dungeonKey)??dungeons[0],data=buildPerformanceTiers(rankings,dungeon.category,dungeon.floor,era),leader=data.entries[0];return <section className="tierPage"><div className="tierIntro"><div><p>{t("observedPerformance")}</p><h2>{t("tierTitle")}</h2><span>{t("tierSub")}</span></div><div className="rankingFilters"><label>{t("dungeon")}<select value={dungeonKey} onChange={event=>setDungeonKey(event.target.value)}>{dungeons.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><SelectEra era={era} setEra={setEra} t={t}/></div></div>{connected&&data.entries.length?<><div className="tierSummary"><div><small>{t("tierCoverage")}</small><b>{data.representedCharacters}/25</b><span>{data.coveragePercent}%</span></div><div><small>{t("confidenceLabel")}</small><b className={data.provisional?"provisional":"consolidated"}>{t(data.provisional?"provisional":"consolidated")}</b><span>{data.provisional?t("provisionalNote"):t("consolidatedNote")}</span></div>{leader&&<div><small>{t("fastestCharacter")}</small><b>{leader.character}</b><span>{timeLabel(leader.time_ms)} · {leader.player_nick}</span></div>}</div><div className="tierBoard">{data.tiers.map(group=><article className={`tierBand tier${group.tier}`} key={group.tier}><strong>{group.tier}</strong><div>{group.entries.length?group.entries.map(entry=><button type="button" onClick={()=>setSelectedRun(entry)} disabled={!entry.video_url&&!onRevoke} key={entry.character}><b><i>#{entry.rank}</i>{entry.character}</b><span>{timeLabel(entry.time_ms)}</span><small>{entry.player_nick}</small><em>{entry.gap_percent===0?t("leader"):t("behindLeader",{percent:entry.gap_percent.toFixed(1)})}</em></button>):<span className="emptyTier">—</span>}</div></article>)}</div><p className="tierMethod">{t("tierMethod")}</p></>:<EmptyState title={connected?t("noTierData"):t("loadingAnalytics")} subtitle={connected?t("noTierDataSub"):t("loadingSub")}/>}<RunEvidenceDialog run={selectedRun} dungeon={dungeon.label} setOpen={open=>{if(!open)setSelectedRun(null)}} onRevoke={onRevoke} t={t}/></section>}

function SubmissionForm({t}:{t:T}) {
  const [videoUrl,setVideoUrl]=useState(""),[character,setCharacter]=useState(""),[dungeon,setDungeon]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState("");
  const submit=(event:FormEvent)=>{event.preventDefault();if(!isYouTubeUrl(videoUrl)){setError(t("invalidVideoUrl"));return}setError("");window.open(buildGitHubSubmissionUrl({videoUrl,character,dungeon,notes}),"_blank","noopener,noreferrer")};
  return <section className="submissionPage"><div className="submissionIntro"><p>{t("communitySubmission")}</p><h2>{t("submitTitle")}</h2><span>{t("submitSub")}</span></div><form className="submissionForm" onSubmit={submit}><label>{t("videoUrl")}<Input type="url" value={videoUrl} onChange={event=>setVideoUrl(event.target.value)} placeholder="https://youtu.be/…" required aria-invalid={Boolean(error)}/>{error&&<small className="submissionError">{error}</small>}</label><div className="submissionFields"><label>{t("optionalCharacter")}<select value={character} onChange={event=>setCharacter(event.target.value)}><option value="">{t("notInformed")}</option>{gameCharacters.map(name=><option value={name} key={name}>{name}</option>)}</select></label><label>{t("optionalDungeon")}<select value={dungeon} onChange={event=>setDungeon(event.target.value)}><option value="">{t("notInformed")}</option>{dungeons.map(item=><option value={item.label} key={item.key}>{item.label}</option>)}</select></label></div><label>{t("notes")}<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder={t("notesPlaceholder")} rows={4}/></label><div className="submissionNotice"><b>GitHub</b><span>{t("submissionGitHubNote")}</span></div><button className="submitRunButton" type="submit">＋ {t("sendForReview")}</button></form></section>
}


function Queue({runs,sel,setSel,decide,t}:{runs:Run[],sel:Run|null,setSel:(r:Run)=>void,decide:(x:boolean,timeMs?:number)=>void,t:T}){
  const pageSize=20,[rawPage,setPage]=useState(1),[qualityFilter,setQualityFilter]=useState<QualityFilter>("all"),[characterFilter,setCharacterFilter]=useState("all"),[dungeonFilter,setDungeonFilter]=useState("all"),[search,setSearch]=useState(""),[sort,setSort]=useState("priority");
  const characters=useMemo(()=>[...new Set(runs.map(run=>run.character).filter((name):name is string=>Boolean(name)))].sort(),[runs]);
  const dungeonOptions=useMemo(()=>[...new Map(runs.filter(run=>run.category&&run.floor!==null).map(run=>[`${run.category}:${run.floor}`,run.map])).entries()].sort((a,b)=>a[1].localeCompare(b[1])),[runs]);
  const filtered=useMemo(()=>runs.filter(run=>matchesQualityFilter(run,qualityFilter))
    .filter(run=>characterFilter==="all"||run.character===characterFilter)
    .filter(run=>dungeonFilter==="all"||`${run.category}:${run.floor}`===dungeonFilter)
    .filter(run=>!search||`${run.title} ${run.user} ${run.char} ${run.map}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
    .sort((a,b)=>sort==="confidence"?a.confidence-b.confidence:sort==="newest"?String(b.publishedAt??b.createdAt).localeCompare(String(a.publishedAt??a.createdAt)):qualityPriority(b)-qualityPriority(a)||a.confidence-b.confidence),[runs,qualityFilter,characterFilter,dungeonFilter,search,sort]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),page=Math.min(rawPage,pages),visible=filtered.slice((page-1)*pageSize,page*pageSize),visibleSelection=sel&&filtered.some(run=>run.id===sel.id)?sel:null;
  const chooseIssue=(filter:QualityFilter)=>{setQualityFilter(filter);setPage(1)};
  return <><QualityPanel runs={runs} active={qualityFilter} choose={chooseIssue} t={t}/><section className="qualityFilters"><label><span>{t("searchCandidates")}</span><Input value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder={t("searchPlaceholder")}/></label><label><span>{t("character")}</span><select value={characterFilter} onChange={event=>{setCharacterFilter(event.target.value);setPage(1)}}><option value="all">{t("allCharacters")}</option>{characters.map(name=><option value={name} key={name}>{name}</option>)}</select></label><label><span>{t("dungeon")}</span><select value={dungeonFilter} onChange={event=>{setDungeonFilter(event.target.value);setPage(1)}}><option value="all">{t("allCategories")}</option>{dungeonOptions.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label><span>{t("sortBy")}</span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="priority">{t("highestPriority")}</option><option value="confidence">{t("lowestConfidence")}</option><option value="newest">{t("newestFirst")}</option></select></label><strong>{t("filteredResults",{count:filtered.length})}</strong></section><div className="columns"><section className="panel queue"><div className="panelHead"><div><h2>{t("realCandidates")}</h2><p>{t("foundAutomatically")}</p></div><span className="pageCount">{t("pageOf",{page,pages})}</span></div>{visible.length?visible.map(r=>{const issues=qualityIssues(r);return <button className={visibleSelection?.id===r.id?"candidate chosen":"candidate"} onClick={()=>setSel(r)} key={r.id}><Thumb r={r}/><div className="info"><div><b>{r.char} · {r.map}</b><em className={r.time!=="—"?"good":"slow"}>{runStatus(r.status,t)}</em></div><p>{r.title}</p><small>{r.user} · YouTube</small><span className="issueTags">{issues.slice(0,3).map(issue=><i className={issue} key={issue}>{qualityIssueLabel(issue,t)}</i>)}</span><span className="meter"><i style={{width:r.conf+"%"}}/><small>{r.conf}%</small></span></div></button>}):<EmptyState title={t("noQualityResults")} subtitle={t("adjustQualityFilters")}/>}<div className="queuePagination"><button type="button" disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>← {t("previous")}</button><span>{t("pageOf",{page,pages})}</span><button type="button" disabled={page===pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>{t("next")} →</button></div></section><section className="panel review">{visibleSelection?<Review key={visibleSelection.id} r={visibleSelection} decide={decide} t={t}/>:<div className="empty"><b>✓</b><h3>{t("selectCandidate")}</h3><p>{t("chooseFilteredVideo")}</p></div>}</section></div></>
}

function QualityPanel({runs,active,choose,t}:{runs:Run[],active:QualityFilter,choose:(filter:QualityFilter)=>void,t:T}){
  const cards:[QualityFilter,MessageKey,MessageKey][]=[
    ["all","qualityAll","qualityAllNote"],
    ["classification","qualityClassification","qualityClassificationNote"],
    ["time","qualityTime","qualityTimeNote"],
    ["ocr_error","qualityOcrError","qualityOcrErrorNote"],
    ["ocr_no_consensus","qualityNoConsensus","qualityNoConsensusNote"],
    ["risk","qualityRisks","qualityRisksNote"],
  ];
  return <section className="qualityPanel"><div className="qualityHeading"><div><p>{t("dataQuality")}</p><h2>{t("qualityTitle")}</h2><span>{t("qualitySub")}</span></div><em>{t("qualityPending",{count:runs.length})}</em></div><div className="qualityCards">{cards.map(([filter,label,note])=>{const count=filter==="all"?runs.length:runs.filter(run=>matchesQualityFilter(run,filter)).length;return <button type="button" className={active===filter?"active":""} onClick={()=>choose(filter)} key={filter}><small>{t(label)}</small><b>{count}</b><span>{t(note)}</span></button>})}</div></section>
}
function Review({r,decide,t}:{r:Run,decide:(x:boolean,timeMs?:number)=>void,t:T}){const initial=splitTimeLabel(r.time),[minutes,setMinutes]=useState(initial.minutes),[seconds,setSeconds]=useState(initial.seconds),[milliseconds,setMilliseconds]=useState(initial.milliseconds),millis=parseTimeParts({minutes,seconds,milliseconds}),valid=millis!==null,touched=minutes!==""||seconds!==""||milliseconds!=="";return <><div className="reviewHead"><div><span>{t("candidateReview")}</span><h2>{r.char} · {r.map}</h2></div><em className={valid?"good":"slow"}>{valid?t("confirmedTime"):t("requiresTime")}</em></div><div className="video realVideo"><iframe src={`https://www.youtube.com/embed/${r.videoId}`} title={r.title} allowFullScreen/></div><h3 className="title">{r.title}</h3><div className="details"><Box k={t("detectedTime")} v={r.time}/><Box k={t("currentRecord")} v={r.current}/><Box k={t("fieldConfidence")} v={`${r.conf}%`}/><Box k={t("channel")} v={r.user}/></div><div className="timeEditor"><label>{t("confirmedTimeLabel")}</label><div className="timeParts"><Input value={minutes} onChange={event=>setMinutes(digitsOnly(event.target.value,2))} placeholder="00" inputMode="numeric" pattern="[0-9]*" aria-label={t("minutes")}/><span>:</span><Input value={seconds} onChange={event=>setSeconds(digitsOnly(event.target.value,2))} placeholder="00" inputMode="numeric" pattern="[0-9]*" aria-label={t("seconds")} aria-invalid={seconds!==""&&Number(seconds)>59}/><span>.</span><Input value={milliseconds} onChange={event=>setMilliseconds(digitsOnly(event.target.value,3))} placeholder="000" inputMode="numeric" pattern="[0-9]*" aria-label={t("milliseconds")}/></div><small className={touched&&!valid?"invalid":""}>{touched&&!valid?t("mobileInvalidTime"):t("timePartsHint")}</small></div><div className="checks"><h3>{t("checklist")}</h3>{["character","dungeon","time","solo","noPotions"].map((key,i)=><label key={key}><input type="checkbox" defaultChecked={i<2||(i===2&&valid)}/>{t(key as MessageKey)}</label>)}</div><div className="decision"><button onClick={()=>decide(false)}>✕ {t("reject")}</button><button className="approve" disabled={!valid} onClick={()=>decide(true,millis??undefined)}>✓ {valid?t("approve"):t("enterTime")}</button></div></>}

function SelectEra({era,setEra,t}:{era:string,setEra:(era:string)=>void,t:T}){return <label>{t("period")}<select value={era} onChange={event=>setEra(event.target.value)}><option value="all">{t("allEras")}</option><option value="current">{t("currentEra")}</option><option value="syntaxii_2026_archive">{t("archive")}</option></select></label>}
function Card({icon,label,val,sub}:{icon:string,label:string,val:string,sub:string}){return <article><i>{icon}</i><div><small>{label}</small><b>{val}</b><p>{sub}</p></div></article>}
function Metric({label,value,note}:{label:string,value:string,note:string}){return <article><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function Thumb({r}:{r:Run}){return <div className="thumb realThumb" style={{backgroundImage:`linear-gradient(#07101a44,#07101abb),url(https://i.ytimg.com/vi/${r.videoId}/hqdefault.jpg)`}}><i>▶</i><small>{r.time}</small></div>}
function Box({k,v}:{k:string,v:string}){return <div><small>{k}</small><b>{v}</b></div>}
function EmptyState({title,subtitle}:{title:string,subtitle:string}){return <div className="rankingEmpty"><b>{title}</b><span>{subtitle}</span></div>}
function runStatus(status:string,t:T){return status==="time_required"?t("requiresTime"):status==="ready_for_review"?t("waiting"):t("reviewFields")}
function qualityIssueLabel(issue:QualityIssue,t:T){const keys:Record<QualityIssue,MessageKey>={classification:"issueClassification",time:"issueTime",ocr_error:"issueOcrError",ocr_no_consensus:"issueNoConsensus",duplicate:"issueDuplicate",outlier:"issueOutlier",low_confidence:"issueLowConfidence"};return t(keys[issue])}
function shortDungeon(category:string){return({void_invasion:"Invasion",void_taint:"Taint",void_nightmare:"Nightmare",void_apocalypse:"Apocalypse",tower_of_disappearance:"Tower",duel_4:"Duel 4",loj_unlimited:"LoJ"}as Record<string,string>)[category]??category}
function bestCoverageInsight(boards:ReturnType<typeof buildAnalytics>["boards"],t:T){const best=[...boards].sort((a,b)=>b.representedCharacters-a.representedCharacters||b.filledSlots-a.filledSlots)[0];return best&&best.filledSlots?t("bestCoverage",{dungeon:best.label,count:best.representedCharacters}):t("noRunsPeriod")}
function coverageRecommendation(boards:ReturnType<typeof buildAnalytics>["boards"],t:T){const target=boards.filter(board=>board.filledSlots>0).sort((a,b)=>a.representedCharacters-b.representedCharacters||a.filledSlots-b.filledSlots)[0];return target?t("gapRecommendation",{dungeon:target.label,count:target.representedCharacters,total:gameCharacters.length}):t("selectPeriod")}
function formatDate(value:string,locale:Locale){const date=new Date(value.length===10?`${value}T12:00:00Z`:value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat({pt:"pt-BR",en:"en-US",ko:"ko-KR",th:"th-TH"}[locale],{day:"2-digit",month:"short",year:"numeric"}).format(date)}
