"use client";

import {useEffect, useMemo, useState, type CSSProperties} from "react";
import {ParserLab} from "./parser-lab";
import {Input} from "@/components/ui/input";
import {Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle} from "@/components/ui/dialog";
import {buildAnalytics, gameCharacters} from "@/lib/analytics";
import {localeNames, translator, type Locale, type MessageKey} from "@/lib/i18n";
import {buildRecordProgression, topRankingsByCharacter, type RankingRow} from "@/lib/ranking";
import {getVideoPreview} from "@/lib/video";

declare const __PUBLIC_READ_ONLY__: boolean;
const publicReadOnly=typeof __PUBLIC_READ_ONLY__!=="undefined"&&__PUBLIC_READ_ONLY__;
type Tab="overview"|"queue"|"rankings"|"parser"|"history";
type T=ReturnType<typeof translator>;
type Run={id:number;user:string;char:string;map:string;time:string;status:string;conf:number;videoId:string;title:string;current:string};
type ApiCandidate={id:number;video_id:string;title:string;channel:string|null;character:string|null;category:string|null;floor:number|null;time_ms:number|null;confidence:number;status:string};

const demoData:Run[]=[
  {id:1,user:"Borkaz",char:"Ereb",map:"Void Invasion · 3F",time:"01:32",status:"ready_for_review",conf:98,videoId:"WZeUJAw4pmU",title:"Ereb | Vazio (Invasão) 3f (1'32) | Grand Chase Classic",current:"—"},
  {id:2,user:"Borkaz",char:"Ereb",map:"Void Nightmare · 4F",time:"—",status:"time_required",conf:86,videoId:"V6O_9x6QTvw",title:"Ereb | Vazio (Pesadelo) 4F | Grand Chase Classic",current:"—"},
];
const dungeons=[
  {key:"void_invasion:3",category:"void_invasion",floor:3,label:"Void Invasion · 3F"},
  {key:"void_taint:3",category:"void_taint",floor:3,label:"Void Taint · 3F"},
  {key:"void_nightmare:4",category:"void_nightmare",floor:4,label:"Void Nightmare · 4F"},
  {key:"void_apocalypse:3",category:"void_apocalypse",floor:3,label:"Void Apocalypse · 3F"},
  {key:"tower_of_disappearance:0",category:"tower_of_disappearance",floor:0,label:"Tower of Disappearance · Hard"},
  {key:"duel_4:0",category:"duel_4",floor:0,label:"Duel 4"},
  {key:"loj_unlimited:0",category:"loj_unlimited",floor:0,label:"LoJ Unlimited"},
];
const tabKeys:Record<Tab,MessageKey>={overview:"overview",queue:"queue",rankings:"rankings",parser:"parser",history:"history"};
const tabIcons:Record<Tab,string>={overview:"⌁",queue:"▣",rankings:"♕",parser:"⌘",history:"↗"};
const categoryName=(value:string|null)=>value?value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";
const timeLabel=(ms:number|null)=>ms===null?"—":`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`;
const parseTime=(value:string)=>{const match=value.trim().match(/^(\d{1,2})\s*[:']\s*([0-5]\d)(?:[.,](\d{1,3}))?$/);if(!match)return null;const millis=match[3]?Number(match[3].padEnd(3,"0")):0,result=(Number(match[1])*60+Number(match[2]))*1000+millis;return result>0?result:null};
const toRun=(r:ApiCandidate):Run=>({id:r.id,user:r.channel??"—",char:r.character??"—",map:`${categoryName(r.category)}${r.floor?` · ${r.floor}F`:""}`,time:timeLabel(r.time_ms),status:r.status,conf:Math.round(r.confidence*100),videoId:r.video_id,title:r.title,current:"—"});

export default function Home(){
  const[locale,setLocale]=useState<Locale>("pt"),[tab,setTab]=useState<Tab>(publicReadOnly?"overview":"queue"),[runs,setRuns]=useState<Run[]>(publicReadOnly?[]:demoData),[sel,setSel]=useState<Run|null>(publicReadOnly?null:demoData[0]),[rankings,setRankings]=useState<RankingRow[]>([]),[history,setHistory]=useState<RankingRow[]>([]),[connected,setConnected]=useState(false),[msg,setMsg]=useState("");
  const t=translator(locale),tabs:Tab[]=publicReadOnly?["overview","rankings","history"]:["overview","queue","rankings","parser","history"],dataUrl=publicReadOnly?"/candidates.json":"/api/candidates";
  useEffect(()=>{const stored=localStorage.getItem("gc-radar-locale") as Locale|null,detected=navigator.language.startsWith("ko")?"ko":navigator.language.startsWith("th")?"th":navigator.language.startsWith("en")?"en":"pt",next=stored&&stored in localeNames?stored:detected;setLocale(next);document.documentElement.lang=next},[]);
  useEffect(()=>{fetch(dataUrl,{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();const body=await response.json();const liveRuns=(body.candidates??[] as ApiCandidate[]).map(toRun);setRuns(liveRuns);setSel(liveRuns[0]??null);setRankings(body.rankings??[]);setHistory(body.history??body.rankings??[]);setConnected(true)}).catch(()=>setConnected(false))},[dataUrl]);
  const changeLocale=(next:Locale)=>{setLocale(next);localStorage.setItem("gc-radar-locale",next);document.documentElement.lang=next};
  const flash=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(""),2500)};
  const decide=async(ok:boolean,timeMs?:number)=>{if(!sel)return;try{const response=await fetch(`/api/candidates/${sel.id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approved:ok,time_ms:timeMs})});if(!response.ok)throw new Error((await response.json()).error);setRuns(current=>current.filter(x=>x.id!==sel.id));setSel(null);flash(ok?t("approve"):t("reject"))}catch(error){flash(error instanceof Error?error.message:t("unavailable"))}};
  return <main><aside><div className="brand"><i>◎</i><span><b>GC Run Radar</b><small>Speedrun intelligence</small></span></div><nav>{tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}><i>{tabIcons[item]}</i><span>{t(tabKeys[item])}</span>{item==="queue"&&<em>{runs.length}</em>}</button>)}</nav><div className="profile"><i>{publicReadOnly?"GC":"GS"}</i><span><b>{publicReadOnly?t("publicAccess"):"Gabriel"}</b><small>{publicReadOnly?t("readOnly"):t("admin")}</small></span></div></aside>
    <section className="work"><header><div><p>{t(publicReadOnly?"community":"monitoring")}</p><h1>{t(tabKeys[tab])}</h1></div><div className="headerActions"><span className="live">● {connected?t(publicReadOnly?"updated":"connected"):t("unavailable")}</span><label className="languageControl"><span>{t("language")}</span><select value={locale} onChange={event=>changeLocale(event.target.value as Locale)} aria-label={t("language")}>{(Object.keys(localeNames) as Locale[]).map(code=><option value={code} key={code}>{localeNames[code]}</option>)}</select></label><button onClick={()=>location.reload()}>⌕ {t("refresh")}</button></div></header>
      {tab==="overview"?<Analytics rankings={rankings} connected={connected} t={t}/>:tab==="queue"&&!publicReadOnly?<Queue runs={runs} sel={sel} setSel={setSel} decide={decide} t={t}/>:tab==="rankings"?<Ranking rankings={rankings} connected={connected} t={t}/>:tab==="parser"&&!publicReadOnly?<ParserLab t={t}/>:<History rows={history} connected={connected} locale={locale} t={t}/>}<footer><a href="https://syntax817.github.io/leaderboard/" target="_blank" rel="noreferrer">{t("inspired")}</a><span>{publicReadOnly?t("publicFooter"):connected?t("queueFooter",{count:runs.length}):t("unavailable")}</span></footer></section>{msg&&<div className="toast">✓ {msg}</div>}</main>
}

function Analytics({rankings,connected,t}:{rankings:RankingRow[],connected:boolean,t:T}){const[era,setEra]=useState("all"),data=buildAnalytics(rankings,dungeons,era),eraLabel=era==="current"?t("currentEra"):era==="syntaxii_2026_archive"?t("archive"):t("allEras");return <section className="analyticsPage"><div className="analyticsIntro"><div><p>{t("datasetCoverage")}</p><h2>{t("panorama")}</h2><span>{t("panoramaSub")}</span></div><SelectEra era={era} setEra={setEra} t={t}/></div>{!connected?<EmptyState title={t("loadingAnalytics")} subtitle={t("loadingSub")}/>:<><section className="analyticsStats"><Metric label={t("verifiedRuns")} value={String(data.verifiedRuns)} note={eraLabel}/><Metric label={t("characters")} value={`${data.representedCharacters}/${gameCharacters.length}`} note={t("withRun")}/><Metric label={t("uniquePlayers")} value={String(data.uniquePlayers)} note={t("identifiedNicks")}/><Metric label={t("topFilled")} value={`${data.overallCoveragePercent}%`} note={t("positions",{filled:data.totalFilledSlots,total:data.totalSlots})}/></section><section className="analyticsGrid"><article className="coveragePanel"><div className="analyticsHead"><div><small>{t("coverageDungeon")}</small><h3>{t("rankingDepth")}</h3></div><span>{t("withData",{active:data.activeDungeons,total:dungeons.length})}</span></div><div className="dungeonBars">{data.boards.map(board=><div className="dungeonBar" key={board.key}><div><strong>{board.label}</strong><small>{t("characterCount",{count:board.representedCharacters,filled:board.filledSlots})}</small></div><b>{board.coveragePercent}%</b><span><i style={{width:`${board.coveragePercent}%`}}/></span></div>)}</div></article><article className="insightPanel"><small>{t("quickRead")}</small><h3>{bestCoverageInsight(data.boards,t)}</h3><p>{coverageRecommendation(data.boards,t)}</p><div><span>0</span><i/><span>1</span><i/><span>2</span><i/><span>3</span><i/><span>4 {t("times")}</span></div></article></section><section className="heatmapPanel"><div className="analyticsHead"><div><small>{t("matrix")}</small><h3>{t("coverageMap")}</h3></div><span>{t("cellHelp")}</span></div><div className="heatmapScroll"><div className="heatmap" style={{"--dungeon-count":dungeons.length} as CSSProperties}><b className="heatCorner">{t("character")}</b>{dungeons.map(dungeon=><b className="heatColumn" title={dungeon.label} key={dungeon.key}>{shortDungeon(dungeon.category)}</b>)}{gameCharacters.map(character=><div className="heatRow" key={character}><strong>{character}</strong>{data.boards.map(board=>{const count=board.byCharacter.get(character)??0;return <span className={`heatCell level${count}`} title={`${character} · ${board.label}: ${count}/4`} aria-label={`${character}, ${board.label}, ${count}/4`} key={board.key}>{count}</span>})}</div>)}</div></div><p className="analyticsNote">{t("emptyPriority")}</p></section></>}</section>}

function History({rows,connected,locale,t}:{rows:RankingRow[],connected:boolean,locale:Locale,t:T}){const[era,setEra]=useState("all"),[dungeonKey,setDungeonKey]=useState(dungeons[0].key),[character,setCharacter]=useState("all"),dungeon=dungeons.find(item=>item.key===dungeonKey)??dungeons[0],characters=useMemo(()=>[...new Set(rows.filter(row=>row.category===dungeon.category&&row.floor===dungeon.floor).map(row=>row.character))].sort((a,b)=>a.localeCompare(b)),[rows,dungeon.category,dungeon.floor]),events=buildRecordProgression(rows,dungeon.category,dungeon.floor,character,era),current=character==="all"?null:events[0];useEffect(()=>{if(character!=="all"&&!characters.includes(character))setCharacter("all")},[characters,character]);return <section className="historyPage"><div className="historyIntro"><div><p>{dungeon.label.toUpperCase()}</p><h2>{t("historyTitle")}</h2><span>{t("historySub")}</span></div><div className="historyFilters"><label>{t("dungeon")}<select value={dungeonKey} onChange={event=>setDungeonKey(event.target.value)}>{dungeons.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><label>{t("chooseCharacter")}<select value={character} onChange={event=>setCharacter(event.target.value)}><option value="all">{t("allCharacters")}</option>{characters.map(name=><option value={name} key={name}>{name}</option>)}</select></label><SelectEra era={era} setEra={setEra} t={t}/></div></div>{connected&&events.length?<><div className="historySummary"><span>{t("recordChanges",{count:events.length})}</span>{current&&<b>{t("fastestNow",{time:timeLabel(current.time_ms)})}</b>}</div><div className="timeline">{events.map(event=><article key={event.id}><i/><div className="timelineDate">{event.event_at?formatDate(event.event_at,locale):t("unknownDate")}</div><div className="timelineCard"><div><small>{event.era_key==="current"?t("currentEra"):t("archive")}</small><h3>{event.character} · {event.player_nick}</h3><span>{event.improvement_ms===null?t("firstRecord"):t("improvedBy",{seconds:(event.improvement_ms/1000).toFixed(event.improvement_ms%1000?1:0)})}</span></div><time>{timeLabel(event.time_ms)}</time>{event.video_url&&<a href={event.video_url} target="_blank" rel="noreferrer">▶ {t("watch")}</a>}</div></article>)}</div></>:<EmptyState title={connected?t("noHistory"):t("loadingAnalytics")} subtitle={connected?t("noHistorySub"):t("loadingSub")}/>}</section>}

function Ranking({rankings,connected,t}:{rankings:RankingRow[],connected:boolean,t:T}){const[era,setEra]=useState("all"),[dungeonKey,setDungeonKey]=useState(dungeons[0].key),[selectedRun,setSelectedRun]=useState<RankingRow|null>(null),dungeon=dungeons.find(x=>x.key===dungeonKey)??dungeons[0],groups=topRankingsByCharacter(rankings,dungeon.category,dungeon.floor,era);return <section className="rankingPage"><div className="rankingIntro"><div><p>{dungeon.label.toUpperCase()}</p><h2>{t("topByCharacter")}</h2><span>{t("rankingSub")}</span></div><div className="rankingFilters"><label>{t("dungeon")}<select value={dungeonKey} onChange={e=>setDungeonKey(e.target.value)}>{dungeons.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><SelectEra era={era} setEra={setEra} t={t}/></div></div><div className="eraNote"><b>{era==="current"?t("currentEra"):era==="all"?t("generalHistory"):t("archive")}</b><span>{era==="current"?t("currentEraNote"):t("archiveNote")}</span></div>{groups.length?<div className="characterGrid">{groups.map(group=><article className="characterBoard" style={{"--character":"#59e1d9"} as CSSProperties} key={group.character}><header><div><small>{t("character").toUpperCase()}</small><h3>{group.character}</h3></div><span>{group.runs.length}/4 {t("times")}</span></header><div className="podium">{Array.from({length:4},(_,i)=>{const run=group.runs[i];return <div className={i===0&&run?"rankRow champion":"rankRow"} key={i}><b>#{i+1}</b>{run?<><span><button className="rankNick" type="button" onClick={()=>setSelectedRun(run)} disabled={!run.video_url} aria-label={t("openRunVideo",{nick:run.player_nick})}>{run.player_nick}<i aria-hidden="true">▶</i>{i===0&&<em>{t("record")}</em>}</button><small>{run.video_url?t("clickForEvidence"):t("verified")}</small></span><time>{timeLabel(run.time_ms)}</time></>:<><span className="open"><strong>{t("openSlot")}</strong><small>{t("waitingRun")}</small></span><time>—</time></>}</div>})}</div></article>)}</div>:<EmptyState title={connected?t("noApproved"):t("loadingAnalytics")} subtitle={connected?t("candidatesFirst"):t("loadingSub")}/>}<p className="rankingFootnote">{t("openSlotsNote")}</p><RunEvidenceDialog run={selectedRun} dungeon={dungeon.label} setOpen={open=>{if(!open)setSelectedRun(null)}} t={t}/></section>}

function RunEvidenceDialog({run,dungeon,setOpen,t}:{run:RankingRow|null,dungeon:string,setOpen:(open:boolean)=>void,t:T}){const preview=run?.video_url?getVideoPreview(run.video_url):null;return <Dialog open={run!==null} onOpenChange={setOpen}><DialogContent className="runEvidenceDialog"><DialogHeader><span className="evidenceEyebrow">{t("runEvidence")}</span><DialogTitle>{run?.player_nick??"—"}</DialogTitle><DialogDescription>{run?t("evidenceSummary",{character:run.character,dungeon,time:timeLabel(run.time_ms)}):""}</DialogDescription></DialogHeader>{run&&preview&&<><a className={`evidencePreview${preview.thumbnailUrl?" hasThumbnail":""}`} href={preview.watchUrl} target="_blank" rel="noreferrer" aria-label={t("watchOn",{platform:preview.platform})}>{preview.thumbnailUrl?<img src={preview.thumbnailUrl} alt={t("videoThumbnail",{nick:run.player_nick})}/>:<div><b>{preview.platform}</b><span>{t("previewUnavailable")}</span></div>}<i aria-hidden="true">▶</i><em>{timeLabel(run.time_ms)}</em></a><div className="evidenceMeta"><div><small>{t("character")}</small><b>{run.character}</b></div><div><small>{t("dungeon")}</small><b>{dungeon}</b></div><div><small>{t("channel")}</small><b>{run.channel??run.player_nick}</b></div><div><small>{t("confirmedTimeLabel")}</small><b>{timeLabel(run.time_ms)}</b></div></div><a className="watchEvidence" href={preview.watchUrl} target="_blank" rel="noreferrer">▶ {t("watchOn",{platform:preview.platform})}</a></>}</DialogContent></Dialog>}

function Queue({runs,sel,setSel,decide,t}:{runs:Run[],sel:Run|null,setSel:(r:Run)=>void,decide:(x:boolean,timeMs?:number)=>void,t:T}){return <><section className="stats"><Card icon="◷" label={t("waiting")} val={String(runs.length)} sub={t("videos")}/><Card icon="♕" label={t("titleTime")} val={String(runs.filter(r=>r.time!=="—").length)} sub={t("automatic")}/><Card icon="◎" label={t("pendingTime")} val={String(runs.filter(r=>r.time==="—").length)} sub={t("ocrHuman")}/></section><div className="columns"><section className="panel queue"><div className="panelHead"><div><h2>{t("realCandidates")}</h2><p>{t("foundAutomatically")}</p></div><select><option>{t("allCategories")}</option></select></div>{runs.map(r=><button className={sel?.id===r.id?"candidate chosen":"candidate"} onClick={()=>setSel(r)} key={r.id}><Thumb r={r}/><div className="info"><div><b>{r.char} · {r.map}</b><em className={r.time!=="—"?"good":"slow"}>{runStatus(r.status,t)}</em></div><p>{r.title}</p><small>{r.user} · YouTube</small><span className="meter"><i style={{width:r.conf+"%"}}/><small>{r.conf}%</small></span></div></button>)}</section><section className="panel review">{sel?<Review key={sel.id} r={sel} decide={decide} t={t}/>:<div className="empty"><b>✓</b><h3>{t("selectCandidate")}</h3><p>{t("chooseVideo")}</p></div>}</section></div></>}
function Review({r,decide,t}:{r:Run,decide:(x:boolean,timeMs?:number)=>void,t:T}){const[time,setTime]=useState(r.time==="—"?"":r.time),millis=parseTime(time),valid=millis!==null;return <><div className="reviewHead"><div><span>{t("candidateReview")}</span><h2>{r.char} · {r.map}</h2></div><em className={valid?"good":"slow"}>{valid?t("confirmedTime"):t("requiresTime")}</em></div><div className="video realVideo"><iframe src={`https://www.youtube.com/embed/${r.videoId}`} title={r.title} allowFullScreen/></div><h3 className="title">{r.title}</h3><div className="details"><Box k={t("detectedTime")} v={r.time}/><Box k={t("currentRecord")} v={r.current}/><Box k={t("fieldConfidence")} v={`${r.conf}%`}/><Box k={t("channel")} v={r.user}/></div><div className="timeEditor"><label htmlFor={`time-${r.id}`}>{t("confirmedTimeLabel")}</label><Input id={`time-${r.id}`} value={time} onChange={event=>setTime(event.target.value)} placeholder={t("timeExample")} inputMode="decimal" aria-invalid={time.length>0&&!valid}/><small className={time.length>0&&!valid?"invalid":""}>{time.length>0&&!valid?t("invalidTime"):t("checkVideo")}</small></div><div className="checks"><h3>{t("checklist")}</h3>{["character","dungeon","time","solo","noPotions"].map((key,i)=><label key={key}><input type="checkbox" defaultChecked={i<2||(i===2&&valid)}/>{t(key as MessageKey)}</label>)}</div><div className="decision"><button onClick={()=>decide(false)}>✕ {t("reject")}</button><button className="approve" disabled={!valid} onClick={()=>decide(true,millis??undefined)}>✓ {valid?t("approve"):t("enterTime")}</button></div></>}

function SelectEra({era,setEra,t}:{era:string,setEra:(era:string)=>void,t:T}){return <label>{t("period")}<select value={era} onChange={event=>setEra(event.target.value)}><option value="all">{t("allEras")}</option><option value="current">{t("currentEra")}</option><option value="syntaxii_2026_archive">{t("archive")}</option></select></label>}
function Card({icon,label,val,sub}:{icon:string,label:string,val:string,sub:string}){return <article><i>{icon}</i><div><small>{label}</small><b>{val}</b><p>{sub}</p></div></article>}
function Metric({label,value,note}:{label:string,value:string,note:string}){return <article><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function Thumb({r}:{r:Run}){return <div className="thumb realThumb" style={{backgroundImage:`linear-gradient(#07101a44,#07101abb),url(https://i.ytimg.com/vi/${r.videoId}/hqdefault.jpg)`}}><i>▶</i><small>{r.time}</small></div>}
function Box({k,v}:{k:string,v:string}){return <div><small>{k}</small><b>{v}</b></div>}
function EmptyState({title,subtitle}:{title:string,subtitle:string}){return <div className="rankingEmpty"><b>{title}</b><span>{subtitle}</span></div>}
function runStatus(status:string,t:T){return status==="time_required"?t("requiresTime"):status==="ready_for_review"?t("waiting"):t("reviewFields")}
function shortDungeon(category:string){return({void_invasion:"Invasion",void_taint:"Taint",void_nightmare:"Nightmare",void_apocalypse:"Apocalypse",tower_of_disappearance:"Tower",duel_4:"Duel 4",loj_unlimited:"LoJ"}as Record<string,string>)[category]??category}
function bestCoverageInsight(boards:ReturnType<typeof buildAnalytics>["boards"],t:T){const best=[...boards].sort((a,b)=>b.representedCharacters-a.representedCharacters||b.filledSlots-a.filledSlots)[0];return best&&best.filledSlots?t("bestCoverage",{dungeon:best.label,count:best.representedCharacters}):t("noRunsPeriod")}
function coverageRecommendation(boards:ReturnType<typeof buildAnalytics>["boards"],t:T){const target=boards.filter(board=>board.filledSlots>0).sort((a,b)=>a.representedCharacters-b.representedCharacters||a.filledSlots-b.filledSlots)[0];return target?t("gapRecommendation",{dungeon:target.label,count:target.representedCharacters,total:gameCharacters.length}):t("selectPeriod")}
function formatDate(value:string,locale:Locale){const date=new Date(value.length===10?`${value}T12:00:00Z`:value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat({pt:"pt-BR",en:"en-US",ko:"ko-KR",th:"th-TH"}[locale],{day:"2-digit",month:"short",year:"numeric"}).format(date)}
