export type Locale = "pt" | "en" | "ko" | "th";

export const localeNames: Record<Locale, string> = {
  pt: "Português", en: "English", ko: "한국어", th: "ไทย",
};

const messages = {
  pt: {
    overview:"Visão geral", queue:"Fila de validação", rankings:"Rankings", parser:"Parser Lab", history:"Histórico",
    community:"RANKING COMUNITÁRIO", monitoring:"MONITORAMENTO AUTOMÁTICO", updated:"Dados atualizados", connected:"Banco conectado", unavailable:"Dados indisponíveis", refresh:"Atualizar", publicAccess:"Acesso público", readOnly:"Somente leitura", admin:"Administrador", language:"Idioma",
    datasetCoverage:"COBERTURA DO DATASET", panorama:"Panorama dos rankings", panoramaSub:"Onde já temos evidência suficiente e onde as próximas buscas geram mais valor.", period:"PERÍODO", allEras:"Todas as eras", currentEra:"Era atual", archive:"Arquivo Syntaxii 2026", loadingAnalytics:"Carregando dados analíticos", loadingSub:"Os indicadores aparecem assim que a fonte responder.", verifiedRuns:"RUNS VALIDADAS", characters:"PERSONAGENS", withRun:"com pelo menos uma run", uniquePlayers:"JOGADORES ÚNICOS", identifiedNicks:"nicks identificados", topFilled:"TOP 4 PREENCHIDO", positions:"{filled} de {total} posições", coverageDungeon:"COBERTURA POR DUNGEON", rankingDepth:"Profundidade do ranking", withData:"{active}/{total} com dados", characterCount:"{count} personagens · {filled}/100 vagas", quickRead:"LEITURA RÁPIDA", noRunsPeriod:"Ainda não há runs neste período.", bestCoverage:"{dungeon} lidera a cobertura com {count} personagens.", gapRecommendation:"{dungeon} é a dungeon ativa com maior lacuna: apenas {count} de {total} personagens possuem tempo. Ela deve receber prioridade nas próximas buscas.", selectPeriod:"Selecione outro período ou aguarde a primeira coleta validada.", matrix:"MATRIZ PERSONAGEM × DUNGEON", coverageMap:"Mapa de cobertura", cellHelp:"Cada célula mostra posições válidas de 4", character:"Personagem", times:"tempos", emptyPriority:"Células vazias indicam prioridades objetivas para as próximas rodadas do crawler.",
    topByCharacter:"Top 4 por personagem", rankingSub:"Cada personagem disputa apenas com outros jogadores usando o mesmo personagem.", dungeon:"DUNGEON", generalHistory:"Histórico geral", currentEraNote:"Iniciada após a última atualização de balanceamento relevante. Uma nova era preserva os recordes antigos sem misturar regras diferentes.", archiveNote:"Arquivo permanente para consulta; balanceamentos diferentes não devem ser comparados como se fossem a mesma era.", noApproved:"Nenhuma run aprovada nesta seleção", candidatesFirst:"Os candidatos importados aparecem primeiro na fila de validação.", openSlot:"Vaga aberta", waitingRun:"Aguardando run validada", verified:"Verificado", record:"RECORDE", openSlotsNote:"As vagas permanecem abertas até novos vídeos serem aprovados.", clickForEvidence:"Clique para ver a run", openRunVideo:"Abrir vídeo da run de {nick}", runEvidence:"EVIDÊNCIA DA RUN", evidenceSummary:"{character} · {dungeon} · {time}", videoThumbnail:"Miniatura da run de {nick}", previewUnavailable:"Miniatura indisponível nesta plataforma", watchOn:"Assistir no {platform}",
    historyTitle:"Evolução dos recordes", historySub:"Somente melhorias reais entram na linha do tempo.", chooseCharacter:"PERSONAGEM", allCharacters:"Todos os personagens", firstRecord:"Primeiro registro", improvedBy:"Melhorou {seconds}s", noHistory:"Nenhuma evolução encontrada nesta seleção", noHistorySub:"Escolha outra dungeon, personagem ou período.", watch:"Assistir ao vídeo", registeredOn:"Registrado em {date}", unknownDate:"Data não informada", recordChanges:"{count} mudanças de recorde", fastestNow:"Recorde atual: {time}",
    inspired:"Inspirado no Grand Chase Leaderboards criado por Syntaxii ↗", publicFooter:"Visualização pública · administração protegida", queueFooter:"{count} candidatos na fila real",
    waiting:"Aguardando análise", videos:"vídeos candidatos", titleTime:"Tempo no título", automatic:"extração automática", pendingTime:"Tempo pendente", ocrHuman:"OCR ou confirmação humana", realCandidates:"Candidatos reais", foundAutomatically:"Encontrados e processados automaticamente", allCategories:"Todas as categorias", selectCandidate:"Selecione um candidato", chooseVideo:"Escolha um vídeo da fila para revisar.", candidateReview:"ANÁLISE DO CANDIDATO", confirmedTime:"Tempo confirmado", requiresTime:"Requer tempo", detectedTime:"TEMPO DETECTADO", currentRecord:"REGISTRO ATUAL", fieldConfidence:"CONFIANÇA DOS CAMPOS", channel:"CANAL", confirmedTimeLabel:"TEMPO CONFIRMADO", timeExample:"Ex.: 01:32 ou 01:32.450", invalidTime:"Use minutos:segundos, como 01:32.", checkVideo:"Confira no vídeo e corrija se necessário.", checklist:"Checklist de validação", reject:"Rejeitar", approve:"Aprovar entrada", enterTime:"Informe o tempo", yes:"Sim", notInformed:"Não informado",
    pipelineTitle:"O parser precisa de duas rotas", executableParser:"PARSER EXECUTÁVEL", pasteTitle:"Cole um título do vídeo", category:"CATEGORIA", floor:"ANDAR", time:"TEMPO", solo:"SOLO", noPotions:"SEM POÇÕES", unidentified:"Não identificado", confidence:"{value}% de confiança", readyQueue:"Pronto para entrar na fila de validação.", missingTime:"Título classificado; falta obter o tempo no vídeo.", reviewFields:"Revise os campos não identificados.",
  },
  en: {
    overview:"Overview", queue:"Validation queue", rankings:"Rankings", parser:"Parser Lab", history:"History", community:"COMMUNITY RANKING", monitoring:"AUTOMATED MONITORING", updated:"Data updated", connected:"Database connected", unavailable:"Data unavailable", refresh:"Refresh", publicAccess:"Public access", readOnly:"Read only", admin:"Administrator", language:"Language",
    datasetCoverage:"DATASET COVERAGE", panorama:"Ranking overview", panoramaSub:"Where evidence is sufficient and where the next searches create more value.", period:"PERIOD", allEras:"All eras", currentEra:"Current era", archive:"Syntaxii 2026 archive", loadingAnalytics:"Loading analytics", loadingSub:"Indicators appear as soon as the source responds.", verifiedRuns:"VERIFIED RUNS", characters:"CHARACTERS", withRun:"with at least one run", uniquePlayers:"UNIQUE PLAYERS", identifiedNicks:"identified nicknames", topFilled:"TOP 4 FILLED", positions:"{filled} of {total} positions", coverageDungeon:"COVERAGE BY DUNGEON", rankingDepth:"Ranking depth", withData:"{active}/{total} with data", characterCount:"{count} characters · {filled}/100 slots", quickRead:"QUICK READ", noRunsPeriod:"There are no runs in this period yet.", bestCoverage:"{dungeon} leads coverage with {count} characters.", gapRecommendation:"{dungeon} is the active dungeon with the largest gap: only {count} of {total} characters have a time. It should be prioritized in the next searches.", selectPeriod:"Select another period or wait for the first verified collection.", matrix:"CHARACTER × DUNGEON MATRIX", coverageMap:"Coverage map", cellHelp:"Each cell shows valid positions out of 4", character:"Character", times:"runs", emptyPriority:"Empty cells are objective priorities for the crawler's next searches.",
    topByCharacter:"Top 4 by character", rankingSub:"Each character competes only against players using the same character.", dungeon:"DUNGEON", generalHistory:"Overall history", currentEraNote:"Started after the latest relevant balance update. A new era preserves older records without mixing different rules.", archiveNote:"Permanent reference archive; different balance periods should not be treated as equivalent.", noApproved:"No approved run in this selection", candidatesFirst:"Imported candidates appear in the validation queue first.", openSlot:"Open slot", waitingRun:"Waiting for a verified run", verified:"Verified", record:"RECORD", openSlotsNote:"Slots remain open until new videos are approved.", clickForEvidence:"Click to view the run", openRunVideo:"Open {nick}'s run video", runEvidence:"RUN EVIDENCE", evidenceSummary:"{character} · {dungeon} · {time}", videoThumbnail:"Thumbnail for {nick}'s run", previewUnavailable:"Thumbnail unavailable on this platform", watchOn:"Watch on {platform}",
    historyTitle:"Record progression", historySub:"Only actual improvements enter the timeline.", chooseCharacter:"CHARACTER", allCharacters:"All characters", firstRecord:"First record", improvedBy:"Improved by {seconds}s", noHistory:"No record progression in this selection", noHistorySub:"Choose another dungeon, character, or period.", watch:"Watch video", registeredOn:"Recorded on {date}", unknownDate:"Unknown date", recordChanges:"{count} record changes", fastestNow:"Current record: {time}",
    inspired:"Inspired by the Grand Chase Leaderboards created by Syntaxii ↗", publicFooter:"Public view · administration protected", queueFooter:"{count} candidates in the live queue", waiting:"Awaiting review", videos:"video candidates", titleTime:"Time in title", automatic:"automatic extraction", pendingTime:"Time pending", ocrHuman:"OCR or human confirmation", realCandidates:"Real candidates", foundAutomatically:"Found and processed automatically", allCategories:"All categories", selectCandidate:"Select a candidate", chooseVideo:"Choose a video from the queue to review.", candidateReview:"CANDIDATE REVIEW", confirmedTime:"Time confirmed", requiresTime:"Time required", detectedTime:"DETECTED TIME", currentRecord:"CURRENT RECORD", fieldConfidence:"FIELD CONFIDENCE", channel:"CHANNEL", confirmedTimeLabel:"CONFIRMED TIME", timeExample:"E.g. 01:32 or 01:32.450", invalidTime:"Use minutes:seconds, such as 01:32.", checkVideo:"Check the video and correct it if needed.", checklist:"Validation checklist", reject:"Reject", approve:"Approve entry", enterTime:"Enter the time", yes:"Yes", notInformed:"Not provided", pipelineTitle:"The parser needs two paths", executableParser:"LIVE PARSER", pasteTitle:"Paste a video title", category:"CATEGORY", floor:"FLOOR", time:"TIME", solo:"SOLO", noPotions:"NO POTIONS", unidentified:"Not identified", confidence:"{value}% confidence", readyQueue:"Ready for the validation queue.", missingTime:"Title classified; the video time is still missing.", reviewFields:"Review fields that were not identified.",
  },
  ko: {
    overview:"개요", queue:"검증 대기열", rankings:"랭킹", parser:"파서 실험실", history:"기록 이력", community:"커뮤니티 랭킹", monitoring:"자동 모니터링", updated:"데이터 최신 상태", connected:"데이터베이스 연결됨", unavailable:"데이터 없음", refresh:"새로고침", publicAccess:"공개 접속", readOnly:"읽기 전용", admin:"관리자", language:"언어",
    datasetCoverage:"데이터셋 커버리지", panorama:"랭킹 현황", panoramaSub:"데이터가 충분한 곳과 다음 검색이 필요한 곳을 확인합니다.", period:"기간", allEras:"모든 시대", currentEra:"현재 시대", archive:"Syntaxii 2026 아카이브", loadingAnalytics:"분석 데이터 로딩 중", loadingSub:"데이터가 도착하면 지표가 표시됩니다.", verifiedRuns:"검증된 기록", characters:"캐릭터", withRun:"최소 한 개 기록 보유", uniquePlayers:"고유 플레이어", identifiedNicks:"확인된 닉네임", topFilled:"TOP 4 충족률", positions:"{total}개 중 {filled}개", coverageDungeon:"던전별 커버리지", rankingDepth:"랭킹 깊이", withData:"{total}개 중 {active}개 데이터 보유", characterCount:"캐릭터 {count}명 · {filled}/100 자리", quickRead:"요약", noRunsPeriod:"이 기간에는 아직 기록이 없습니다.", bestCoverage:"{dungeon}: 캐릭터 {count}명으로 가장 높은 커버리지입니다.", gapRecommendation:"{dungeon}은 활성 던전 중 공백이 가장 큽니다. {total}명 중 {count}명만 기록이 있어 다음 검색의 우선 대상입니다.", selectPeriod:"다른 기간을 선택하거나 첫 검증 결과를 기다려 주세요.", matrix:"캐릭터 × 던전 매트릭스", coverageMap:"커버리지 맵", cellHelp:"각 셀은 4자리 중 유효 기록 수입니다", character:"캐릭터", times:"기록", emptyPriority:"빈 셀은 다음 크롤러 검색의 우선순위입니다.",
    topByCharacter:"캐릭터별 TOP 4", rankingSub:"같은 캐릭터를 사용한 플레이어끼리만 경쟁합니다.", dungeon:"던전", generalHistory:"전체 이력", currentEraNote:"최근 주요 밸런스 업데이트 이후 시작되었습니다. 이전 기록은 다른 규칙과 섞지 않고 보존합니다.", archiveNote:"영구 참고용 아카이브입니다. 서로 다른 밸런스 기간은 동일하게 비교하지 않습니다.", noApproved:"선택 항목에 승인된 기록이 없습니다", candidatesFirst:"가져온 후보는 먼저 검증 대기열에 표시됩니다.", openSlot:"빈 자리", waitingRun:"검증된 기록 대기 중", verified:"검증됨", record:"기록", openSlotsNote:"새 영상이 승인될 때까지 자리는 비어 있습니다.", clickForEvidence:"클릭하여 영상 보기", openRunVideo:"{nick}의 기록 영상 열기", runEvidence:"기록 증거 영상", evidenceSummary:"{character} · {dungeon} · {time}", videoThumbnail:"{nick} 기록 영상 미리보기", previewUnavailable:"이 플랫폼에서는 미리보기를 제공하지 않습니다", watchOn:"{platform}에서 보기",
    historyTitle:"기록 변천", historySub:"실제로 단축된 기록만 타임라인에 포함됩니다.", chooseCharacter:"캐릭터", allCharacters:"모든 캐릭터", firstRecord:"첫 기록", improvedBy:"{seconds}초 단축", noHistory:"선택 항목에 기록 변천이 없습니다", noHistorySub:"다른 던전, 캐릭터 또는 기간을 선택하세요.", watch:"영상 보기", registeredOn:"{date} 등록", unknownDate:"날짜 정보 없음", recordChanges:"기록 변경 {count}회", fastestNow:"현재 기록: {time}", inspired:"Syntaxii의 Grand Chase Leaderboards에서 영감을 받았습니다 ↗", publicFooter:"공개 보기 · 관리 기능 보호됨", queueFooter:"실시간 후보 {count}개", waiting:"검토 대기", videos:"영상 후보", titleTime:"제목에서 시간 인식", automatic:"자동 추출", pendingTime:"시간 미확인", ocrHuman:"OCR 또는 수동 확인", realCandidates:"실제 후보", foundAutomatically:"자동 검색 및 처리됨", allCategories:"모든 카테고리", selectCandidate:"후보를 선택하세요", chooseVideo:"검토할 영상을 선택하세요.", candidateReview:"후보 검토", confirmedTime:"시간 확인됨", requiresTime:"시간 필요", detectedTime:"감지된 시간", currentRecord:"현재 기록", fieldConfidence:"필드 신뢰도", channel:"채널", confirmedTimeLabel:"확인된 시간", timeExample:"예: 01:32 또는 01:32.450", invalidTime:"분:초 형식으로 입력하세요. 예: 01:32", checkVideo:"영상을 확인하고 필요하면 수정하세요.", checklist:"검증 체크리스트", reject:"거절", approve:"기록 승인", enterTime:"시간 입력", yes:"예", notInformed:"정보 없음", pipelineTitle:"파서는 두 경로가 필요합니다", executableParser:"실행 가능한 파서", pasteTitle:"영상 제목 붙여넣기", category:"카테고리", floor:"층", time:"시간", solo:"솔로", noPotions:"포션 미사용", unidentified:"인식 안 됨", confidence:"신뢰도 {value}%", readyQueue:"검증 대기열에 추가할 준비가 되었습니다.", missingTime:"제목은 분류되었지만 영상 시간이 필요합니다.", reviewFields:"인식되지 않은 필드를 검토하세요.",
  },
  th: {
    overview:"ภาพรวม", queue:"คิวตรวจสอบ", rankings:"อันดับ", parser:"ห้องทดลอง Parser", history:"ประวัติ", community:"อันดับชุมชน", monitoring:"การติดตามอัตโนมัติ", updated:"ข้อมูลเป็นปัจจุบัน", connected:"เชื่อมต่อฐานข้อมูลแล้ว", unavailable:"ไม่มีข้อมูล", refresh:"รีเฟรช", publicAccess:"การเข้าถึงสาธารณะ", readOnly:"อ่านอย่างเดียว", admin:"ผู้ดูแล", language:"ภาษา",
    datasetCoverage:"ความครอบคลุมของชุดข้อมูล", panorama:"ภาพรวมอันดับ", panoramaSub:"ดูว่าจุดใดมีหลักฐานเพียงพอและควรค้นหาเพิ่มเติมที่ใด", period:"ช่วงเวลา", allEras:"ทุกยุค", currentEra:"ยุคปัจจุบัน", archive:"คลัง Syntaxii 2026", loadingAnalytics:"กำลังโหลดข้อมูลวิเคราะห์", loadingSub:"ตัวชี้วัดจะแสดงเมื่อได้รับข้อมูล", verifiedRuns:"รันที่ตรวจสอบแล้ว", characters:"ตัวละคร", withRun:"มีอย่างน้อยหนึ่งรัน", uniquePlayers:"ผู้เล่นไม่ซ้ำ", identifiedNicks:"ชื่อผู้เล่นที่พบ", topFilled:"TOP 4 ที่เติมแล้ว", positions:"{filled} จาก {total} ตำแหน่ง", coverageDungeon:"ความครอบคลุมตามดันเจี้ยน", rankingDepth:"ความลึกของอันดับ", withData:"{active}/{total} มีข้อมูล", characterCount:"{count} ตัวละคร · {filled}/100 ช่อง", quickRead:"สรุป", noRunsPeriod:"ยังไม่มีรันในช่วงเวลานี้", bestCoverage:"{dungeon} ครอบคลุมสูงสุดด้วย {count} ตัวละคร", gapRecommendation:"{dungeon} เป็นดันเจี้ยนที่ยังขาดข้อมูลมากที่สุด: มีเวลาเพียง {count} จาก {total} ตัวละคร ควรค้นหาเป็นลำดับแรก", selectPeriod:"เลือกช่วงเวลาอื่นหรือรอข้อมูลที่ตรวจสอบแล้ว", matrix:"เมทริกซ์ตัวละคร × ดันเจี้ยน", coverageMap:"แผนที่ความครอบคลุม", cellHelp:"แต่ละช่องแสดงจำนวนตำแหน่งที่มีจาก 4", character:"ตัวละคร", times:"รัน", emptyPriority:"ช่องว่างคือเป้าหมายสำคัญสำหรับการค้นหาครั้งถัดไปของ crawler",
    topByCharacter:"Top 4 ตามตัวละคร", rankingSub:"ตัวละครแต่ละตัวแข่งขันกับผู้เล่นที่ใช้ตัวละครเดียวกันเท่านั้น", dungeon:"ดันเจี้ยน", generalHistory:"ประวัติทั้งหมด", currentEraNote:"เริ่มหลังการปรับสมดุลครั้งสำคัญล่าสุด โดยเก็บสถิติเก่าแยกจากกฎใหม่", archiveNote:"คลังถาวรสำหรับอ้างอิง ไม่ควรเปรียบเทียบช่วงสมดุลต่างกันโดยตรง", noApproved:"ไม่มีรันที่อนุมัติในตัวเลือกนี้", candidatesFirst:"รายการที่นำเข้าจะเข้าสู่คิวตรวจสอบก่อน", openSlot:"ช่องว่าง", waitingRun:"รอรันที่ตรวจสอบแล้ว", verified:"ตรวจสอบแล้ว", record:"สถิติ", openSlotsNote:"ช่องจะว่างจนกว่าจะมีวิดีโอใหม่ได้รับอนุมัติ", clickForEvidence:"คลิกเพื่อดูวิดีโอ", openRunVideo:"เปิดวิดีโอรันของ {nick}", runEvidence:"หลักฐานของรัน", evidenceSummary:"{character} · {dungeon} · {time}", videoThumbnail:"ภาพตัวอย่างรันของ {nick}", previewUnavailable:"แพลตฟอร์มนี้ไม่มีภาพตัวอย่าง", watchOn:"ดูบน {platform}",
    historyTitle:"พัฒนาการของสถิติ", historySub:"เฉพาะเวลาที่ดีขึ้นจริงเท่านั้นที่เข้าสู่ไทม์ไลน์", chooseCharacter:"ตัวละคร", allCharacters:"ตัวละครทั้งหมด", firstRecord:"สถิติแรก", improvedBy:"เร็วขึ้น {seconds} วินาที", noHistory:"ไม่พบพัฒนาการของสถิติ", noHistorySub:"เลือกดันเจี้ยน ตัวละคร หรือช่วงเวลาอื่น", watch:"ดูวิดีโอ", registeredOn:"บันทึกเมื่อ {date}", unknownDate:"ไม่ทราบวันที่", recordChanges:"เปลี่ยนสถิติ {count} ครั้ง", fastestNow:"สถิติปัจจุบัน: {time}", inspired:"ได้รับแรงบันดาลใจจาก Grand Chase Leaderboards ของ Syntaxii ↗", publicFooter:"มุมมองสาธารณะ · ระบบผู้ดูแลได้รับการป้องกัน", queueFooter:"ผู้สมัคร {count} รายการในคิว", waiting:"รอตรวจสอบ", videos:"วิดีโอผู้สมัคร", titleTime:"เวลาในชื่อวิดีโอ", automatic:"การดึงอัตโนมัติ", pendingTime:"รอข้อมูลเวลา", ocrHuman:"OCR หรือยืนยันโดยคน", realCandidates:"ผู้สมัครจริง", foundAutomatically:"ค้นหาและประมวลผลอัตโนมัติ", allCategories:"ทุกหมวดหมู่", selectCandidate:"เลือกผู้สมัคร", chooseVideo:"เลือกวิดีโอจากคิวเพื่อตรวจสอบ", candidateReview:"ตรวจสอบผู้สมัคร", confirmedTime:"ยืนยันเวลาแล้ว", requiresTime:"ต้องระบุเวลา", detectedTime:"เวลาที่ตรวจพบ", currentRecord:"สถิติปัจจุบัน", fieldConfidence:"ความมั่นใจของข้อมูล", channel:"ช่อง", confirmedTimeLabel:"เวลาที่ยืนยัน", timeExample:"เช่น 01:32 หรือ 01:32.450", invalidTime:"ใช้รูปแบบ นาที:วินาที เช่น 01:32", checkVideo:"ตรวจสอบวิดีโอและแก้ไขหากจำเป็น", checklist:"รายการตรวจสอบ", reject:"ปฏิเสธ", approve:"อนุมัติ", enterTime:"ระบุเวลา", yes:"ใช่", notInformed:"ไม่ระบุ", pipelineTitle:"Parser ต้องใช้สองเส้นทาง", executableParser:"PARSER ที่ใช้งานได้", pasteTitle:"วางชื่อวิดีโอ", category:"หมวดหมู่", floor:"ชั้น", time:"เวลา", solo:"โซโล", noPotions:"ไม่ใช้โพชั่น", unidentified:"ไม่พบข้อมูล", confidence:"ความมั่นใจ {value}%", readyQueue:"พร้อมเข้าสู่คิวตรวจสอบ", missingTime:"จำแนกชื่อแล้ว แต่ยังต้องอ่านเวลาจากวิดีโอ", reviewFields:"ตรวจสอบช่องที่ยังไม่พบข้อมูล",
  },
} as const;

export type MessageKey = keyof typeof messages.pt;

export function translator(locale: Locale) {
  return (key: MessageKey, values: Record<string, string | number> = {}) => {
    let value: string = messages[locale][key] ?? messages.pt[key];
    for (const [name, replacement] of Object.entries(values)) value = value.replace(`{${name}}`, String(replacement));
    return value;
  };
}
