export type ParsedTitle={character:string|null;category:string|null;floor:number|null;timeMs:number|null;timeLabel:string;solo:boolean;noPotions:boolean;confidence:number;status:"ready_for_review"|"time_required"|"classification_required"};
const chars:[string,string][]=[["rufus","Rufus/Lupus"],["lupus","Rufus/Lupus"],["ley","Ley/Rey"],["rey","Ley/Rey"],["rin","Rin/Lin"],["lin","Rin/Lin"],["lime","Lime/Holy"],["holy","Lime/Holy"],["azin","Asin"],["decane","Decanee"],["아신","Asin"],["อาซิน","Asin"],["엘리시스","Elesis"],["리르","Lire"],["아르메","Arme"],["라스","Lass"],["라이언","Ryan"],["로난","Ronan"],["에이미","Amy"],["진","Jin"],["지크하트","Sieghart"],["마리","Mari"],["디오","Dio"],["제로","Zero"],["레이","Ley/Rey"],["루퍼스","Rufus/Lupus"],["린","Rin/Lin"],["라임","Lime/Holy"],["에델","Edel"],["베이가스","Veigas"],["우노","Uno"],["데카네","Decanee"],["칼리아","Kallia"],["아이리스","Iris"],["아이","Ai"],["에레브","Ereb"],["เอลิซิส","Elesis"],["ลีร์","Lire"],["อาร์เม","Arme"],["ลาส","Lass"],["ไรอัน","Ryan"],["โรแนน","Ronan"],["เอมี่","Amy"],["จิน","Jin"],["ซิกฮาร์ท","Sieghart"],["มารี","Mari"],["ดิโอ","Dio"],["ซีโร่","Zero"],["เลย์","Ley/Rey"],["ลูฟัส","Rufus/Lupus"],["ริน","Rin/Lin"],["ไลม์","Lime/Holy"],["เอเดล","Edel"],["เวกัส","Veigas"],["อูโน","Uno"],["เดคานี","Decanee"],["คัลเลีย","Kallia"],["ไอริส","Iris"],["ไอ","Ai"],["เอเรบ","Ereb"],...["elesis","lire","arme","lass","ryan","ronan","amy","jin","sieghart","mari","dio","zero","asin","edel","veigas","uno","decanee","kallia","ai","iris","ereb"].map(x=>[x,x[0].toUpperCase()+x.slice(1)] as [string,string])];
const cats:[string,string][]=[["void invasion","void_invasion"],["vazio invasao","void_invasion"],["공허 침공","void_invasion"],["보이드 침공","void_invasion"],["วอยด์ อินเวชัน","void_invasion"],["วอยด์ บุก","void_invasion"],["void taint","void_taint"],["vazio contaminacao","void_taint"],["공허 잠식","void_taint"],["วอยด์ เทนต์","void_taint"],["void nightmare","void_nightmare"],["vazio pesadelo","void_nightmare"],["공허 악몽","void_nightmare"],["วอยด์ ไนต์แมร์","void_nightmare"],["void apocalypse","void_apocalypse"],["vazio apocalipse","void_apocalypse"],["공허 종말","void_apocalypse"],["วอยด์ อะพอคคาลิปส์","void_apocalypse"],["tower of disappearance","tower_of_disappearance"],["torre do desaparecimento","tower_of_disappearance"],["infinity cloister stage 4","duel_4"],["duel lv 4","duel_4"],["duel lvl 4","duel_4"],["duel 4","duel_4"],["duelo lv 4","duel_4"],["duelo 4","duel_4"],["loj unlimited","loj_unlimited"],["terra do julgamento ilimitada","loj_unlimited"],["infinity cloister stage 3","infinity_cloister_3"],["land of judgement","land_of_judgement"],["land of judgment","land_of_judgement"],["renak s core champion","renaks_core_champion"],["great explosion of kounat","great_explosion_of_kounat"],["wizard s labyrinth stage 30","wizards_labyrinth_30"],["moonlight village","moonlight_village"],["temple of time","temple_of_time"],["sanctuary of divine beast master mode","sanctuary_divine_beast_master"],["sanctuary of divine beast master","sanctuary_divine_beast_master"],["hall of harmony master mode","hall_of_harmony_master"],["hall of harmony master","hall_of_harmony_master"],["chapel of eternity master","chapel_of_eternity_master"],["path shrouded in darkness master","path_shrouded_darkness_master"],["apocalypse vortex master","apocalypse_vortex_master"],["apocalypse vortex","apocalypse_vortex_master"],["berkas lair","berkas_lair"]];
const plain=(s:string)=>s.toLocaleLowerCase("pt-BR").normalize("NFKC").replace(/[áàãâä]/g,"a").replace(/[éèêë]/g,"e").replace(/[íìîï]/g,"i").replace(/[óòõôö]/g,"o").replace(/[úùûü]/g,"u").replace(/ç/g,"c");
const find=(s:string,list:[string,string][])=>list.find(([a])=>new RegExp("(?:^| )"+a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replaceAll(" ","\\s+")+"(?: |$)","u").test(s))?.[1]??null;
export function parseRunTitle(title:string):ParsedTitle{
  const text=plain(title),words=text.replace(/[^\p{L}\p{M}\p{N}]+/gu," ").replace(/\s+/g," ").trim();
  const character=find(words,chars);
  let category=find(words,cats);
  if(words.includes("angry boss")&&words.includes("archimedia"))category="angry_boss_archimedia";
  else if(words.includes("angry boss")&&words.includes("alcubra"))category="angry_boss_alcubra";
  const fm=words.match(/(?:^|\s)([1-9])\s*(?:f|andar|층|ชั้น)(?:\s|$)/);
  let floor:number|null=fm?Number(fm[1]):null;
  const zeroFloor=["tower_of_disappearance","duel_4","loj_unlimited","infinity_cloister_3","land_of_judgement","renaks_core_champion","great_explosion_of_kounat","wizards_labyrinth_30","moonlight_village","temple_of_time","sanctuary_divine_beast_master","hall_of_harmony_master","chapel_of_eternity_master","path_shrouded_darkness_master","apocalypse_vortex_master","berkas_lair","angry_boss_archimedia","angry_boss_alcubra"];
  if(floor===null&&category&&zeroFloor.includes(category))floor=0;
  const tm=text.match(/(?:^|\D)(\d{1,2})\s*[':]\s*(\d{2})(?:[.,](\d{1,3}))?(?!\d)/);
  const secondsOnly=text.match(/(?:^|\D)(\d{1,3})\s*s(?:ec(?:ond)?s?)?(?!\w)/);
  let timeMs:number|null=null;
  if(tm&&Number(tm[2])<60)timeMs=(Number(tm[1])*60+Number(tm[2]))*1000+Number((tm[3]??"").padEnd(3,"0")||0);
  else if(secondsOnly)timeMs=Number(secondsOnly[1])*1000;
  const score=(character?30:0)+(category?30:0)+(floor!==null?10:0)+(timeMs!==null?25:0)+(/\bsolo\b|sem\s+pocoes|no\s+pot/.test(text)?5:0);
  return{character,category,floor,timeMs,timeLabel:timeMs===null?"Pendente":String(Math.floor(timeMs/60000)).padStart(2,"0")+":"+String(Math.floor(timeMs/1000)%60).padStart(2,"0"),solo:/\bsolo\b/.test(text),noPotions:/sem\s+pocoes|no\s+pot(?:ion)?s?/.test(text),confidence:score,status:character&&category&&floor!==null?(timeMs===null?"time_required":"ready_for_review"):"classification_required"};
}
